FROM node:18-alpine

RUN apk add --no-cache bash sudo

RUN apk add --no-cache bash sudo git openssh-client curl

WORKDIR /app

RUN npm install -g @nestjs/cli

COPY package*.json ./

RUN npm install

COPY . .

RUN chown -R node:node /app

RUN echo "node ALL=(ALL) NOPASSWD: /bin/chown, /bin/rm" >> /etc/sudoers


CMD ["./scripts/entrypoint.sh"]